"""Main backtest runner - orchestrates data fetching, strategy execution, and reporting"""
import sys
from datetime import datetime
import pandas as pd
from data_fetcher import fetch_historical_data, save_data, load_data
from strategies import SPYSwingTradingStrategy


def run_backtest(symbol='SPY', years=2, use_cache=True):
    """
    Run complete backtest

    Args:
        symbol: Stock symbol
        years: Years of historical data
        use_cache: Use cached data if available
    """

    print(f"\n{'='*60}")
    print(f"BACKTEST: {symbol} Swing Trading Strategy")
    print(f"{'='*60}\n")

    # Fetch or load data
    if use_cache:
        df = load_data(symbol, '1Day')
    else:
        df = None

    if df is None or len(df) == 0:
        print(f"Fetching fresh data for {symbol}...")
        df = fetch_historical_data(symbol, timeframe='1Day', years=years)
        if df is None:
            print("Failed to fetch data. Exiting.")
            return None, None, None, None

        # Save for future use
        save_data(df, symbol, '1Day')
    else:
        print(f"Using cached data ({len(df)} bars)")

    # Run backtest
    print(f"\nRunning backtest on {len(df)} bars...")
    strategy = SPYSwingTradingStrategy(initial_capital=100000, position_size=0.1)
    trades, metrics, equity_curve = strategy.backtest(df)

    # Print results
    print(f"\n{'='*60}")
    print("BACKTEST RESULTS")
    print(f"{'='*60}\n")

    print(f"Strategy: {strategy.name}")
    print(f"Data Range: {df.index[0].date()} to {df.index[-1].date()}")
    print(f"Total Bars: {len(df)}\n")

    print("TRADE STATISTICS:")
    print(f"  Total Trades: {metrics['total_trades']}")
    print(f"  Winning Trades: {metrics['winning_trades']}")
    print(f"  Losing Trades: {metrics['losing_trades']}")
    print(f"  Win Rate: {metrics['win_rate']*100:.2f}%")
    print(f"  Avg Return per Trade: {metrics['avg_return_per_trade']*100:.2f}%")
    print(f"  Profit Factor: {metrics['profit_factor']:.2f}\n")

    print("PERFORMANCE:")
    print(f"  Initial Equity: $100,000.00")
    print(f"  Final Equity: ${metrics['final_equity']:,.2f}")
    print(f"  Total Return: {metrics['total_return']*100:.2f}%")
    print(f"  Max Drawdown: {metrics['max_drawdown']*100:.2f}%")
    print(f"  Sharpe Ratio: {metrics['sharpe_ratio']:.2f}\n")

    # Show recent trades
    if len(trades) > 0:
        print("RECENT TRADES (last 10):")
        print(f"{'Entry Date':<12} {'Entry':<10} {'Exit':<10} {'Return':<10} {'Days':<6}")
        print("-" * 50)

        for _, trade in trades.tail(10).iterrows():
            entry_date = trade['entry_date'].strftime('%Y-%m-%d')
            entry_price = f"${trade['entry_price']:.2f}"
            exit_price = f"${trade['exit_price']:.2f}"
            ret = f"{trade['return']*100:.2f}%"
            days = f"{int(trade['days_held'])}"
            print(f"{entry_date:<12} {entry_price:<10} {exit_price:<10} {ret:<10} {days:<6}")

        # Save trades to CSV
        import os
        trades_csv = f"backtest_results/{symbol}_trades_{datetime.now().strftime('%Y%m%d_%H%M%S')}.csv"
        if not os.path.exists('backtest_results'):
            os.makedirs('backtest_results')

        trades.to_csv(trades_csv)
        print(f"\nTrades saved to: {trades_csv}")

    else:
        print("No trades generated by strategy.")

    print(f"\n{'='*60}\n")

    return trades, metrics, equity_curve, df


if __name__ == '__main__':
    # Run backtest
    trades, metrics, equity_curve, df = run_backtest(symbol='SPY', years=2, use_cache=True)
